### PR TITLE
Deleted bots crash game page

### LINKED ISSUE #532: Deleted bots crash game page

### PR DESCRIPTION
**Pull request by Klimonov**

### CODE REVIEW

**Review by EgoriusRus — APPROVED** [review]
LGTM

File: components/AntHiveBotVertical.vue [hunk 1]
```diff
@@ -99,9 +99,6 @@ export default {
         return this.getStringTruncated(this.bot.displayName, 10)
       }
     },
-    getUserAvatar() {
-      return this.user && this.user.avatar
-    },
     getUsername() {
       return this.user && this.user.username
```
Comment (kezlya) [inline components/AntHiveBotVertical.vue:103]: if this.user && this.user.username{ 
return this.user.username
}else {
return "deleted"
}

**Review by kezlya — COMMENTED** [review]
almost there
